version: "2"
services:
  app:
    container_name: Adoptame
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/adoptameAPI
      - DEBUG=adoptameAPI:*
      - JWT_SECRET=Awerqw@#$$WER!@#$$!@%ETWEQR@!!asda123
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"